# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=datetime.datetime(2017, 10, 18, 1, 46, 7, 140982, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
